[package]
name = "sp_model"
version = "0.1.0"
edition = "2021"

[dependencies]
sp_domain = { path = "../sp_domain/" }
sp_model_derive = { path = "../sp_model_derive/" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
illicit = "1.1.2"
